/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.edu.itses.marg.listasyinterfaces.View;
import mx.edu.itses.marg.listasyinterfaces.Controller.VuelosController;
import mx.edu.itses.marg.listasyinterfaces.View.TestListas;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import mx.edu.itses.marg.listasyinterfaces.Modelo.Vuelo;

/**
 *
 * @author mar_6
 */
public class ViewForm extends javax.swing.JFrame {

    
    
    
    
    public ViewForm() {
        initComponents();
        setLocationRelativeTo(null);
        btnOrdenado.addActionListener(e -> mostrarVuelosOrdenados());
        btnUltimo.addActionListener(e -> mostrarUltimoVuelo());
        btnmenor.addActionListener(e -> mostrarVueloMenorPasajeros());
    
  
    }
   private void mostrarVuelosOrdenados() {
        List<Vuelo> vuelos = VuelosController.obtenerVuelos();
        vuelos.sort(Comparator.comparing(Vuelo::getFechaCompleta)); 

        StringBuilder sb = new StringBuilder("Vuelos ordenados por fecha de llegada: \n");
        for (Vuelo vuelo : vuelos) {
            sb.append(vuelo).append("\n");
        }

        txtArea.setText(sb.toString());
    }
   private void mostrarUltimoVuelo() {
        List<Vuelo> vuelos = VuelosController.obtenerVuelos();
        if (vuelos.isEmpty()) {
            txtArea.setText("No hay vuelos registrados.");
            return;
        }

        Vuelo ultimoVuelo = vuelos.stream()
                .max(Comparator.comparing(Vuelo::getFechaCompleta))
                .orElse(null);

        txtArea.setText("Ultimo vuelo en llegar:\n" + (ultimoVuelo != null ? ultimoVuelo : "No hay vuelos."));
    }
    
    private void mostrarVueloMenorPasajeros() {
        List<Vuelo> vuelos = VuelosController.obtenerVuelos();
        if (vuelos.isEmpty()) {
            txtArea.setText("No hay vuelos registrados.");
            return;
        }

        Vuelo menorPasajeros = vuelos.stream()
        .min(Comparator.comparingInt(Vuelo::getNumPasajeros))
        .orElse(null);

        txtArea.setText("Vuelo con menor numero de pasajeros:\n" + (menorPasajeros != null ? menorPasajeros : "No hay vuelos."));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnOrdenado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnUltimo = new javax.swing.JButton();
        btnmenor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Creacion de vuelos");

        jLabel2.setText("Agrega lo solicitado");

        btnOrdenado.setText("Mostrar ordenado");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnUltimo.setText("Mostrar Ultimo");

        btnmenor.setText("Mostrar menor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnOrdenado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUltimo)
                                .addGap(41, 41, 41)
                                .addComponent(btnmenor)
                                .addGap(12, 12, 12)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdenado)
                    .addComponent(btnUltimo)
                    .addComponent(btnmenor))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    

    /**
     * @param args the command line arguments
     */
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrdenado;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton btnmenor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
